#!/bin/bash

# Post-Deployment Configuration Script
# Run this after deploying your smart contract to configure the frontend

echo "🎯 Raffle App - Post-Deployment Setup"
echo "======================================"
echo ""

# Check if .env.local exists
if [ -f ".env.local" ]; then
    echo "⚠️  .env.local already exists. Creating backup..."
    cp .env.local .env.local.backup
    echo "✅ Backup saved as .env.local.backup"
    echo ""
fi

# Prompt for contract address
echo "📝 Please enter your deployed contract address:"
read -p "Contract Address (0x...): " CONTRACT_ADDRESS

# Validate address format
if [[ ! $CONTRACT_ADDRESS =~ ^0x[a-fA-F0-9]{40}$ ]]; then
    echo "❌ Invalid contract address format. Should be 0x followed by 40 hex characters."
    exit 1
fi

# Prompt for network
echo ""
echo "🌐 Which network did you deploy to?"
echo "1) Base Sepolia (testnet)"
echo "2) Base Mainnet"
read -p "Choice (1 or 2): " NETWORK_CHOICE

if [ "$NETWORK_CHOICE" = "1" ]; then
    CHAIN_ID=84532
    NETWORK_NAME="Base Sepolia"
elif [ "$NETWORK_CHOICE" = "2" ]; then
    CHAIN_ID=8453
    NETWORK_NAME="Base Mainnet"
else
    echo "❌ Invalid choice. Exiting."
    exit 1
fi

# Prompt for API keys
echo ""
echo "🔑 Please enter your API keys:"
read -p "Alchemy API Key: " ALCHEMY_KEY
read -p "Coinbase Developer Platform (CDP) API Key: " CDP_KEY
read -p "WalletConnect Project ID: " WALLETCONNECT_ID

# Create .env.local file
cat > .env.local << EOF
# Generated by post-deploy-setup.sh on $(date)

# Smart Contract Configuration
NEXT_PUBLIC_RAFFLE_CORE_ADDRESS=$CONTRACT_ADDRESS
NEXT_PUBLIC_CHAIN_ID=$CHAIN_ID

# Base Blockchain Configuration
NEXT_PUBLIC_ALCHEMY_API_KEY=$ALCHEMY_KEY

# OnchainKit Configuration
NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME=Raffles
NEXT_PUBLIC_CDP_API_KEY=$CDP_KEY

# WalletConnect Configuration
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=$WALLETCONNECT_ID

# Neynar (Farcaster) Configuration - Optional
# NEYNAR_API_KEY=
# NEXT_PUBLIC_NEYNAR_CLIENT_ID=

# Application URL
NEXT_PUBLIC_APP_URL=http://localhost:3000

# Basescan API Key - Optional
# BASESCAN_API_KEY=
EOF

echo ""
echo "✅ Configuration complete!"
echo ""
echo "📋 Summary:"
echo "  Network: $NETWORK_NAME"
echo "  Chain ID: $CHAIN_ID"
echo "  Contract: $CONTRACT_ADDRESS"
echo ""
echo "🔗 View your contract:"
if [ "$CHAIN_ID" = "84532" ]; then
    echo "  https://sepolia.basescan.org/address/$CONTRACT_ADDRESS"
else
    echo "  https://basescan.org/address/$CONTRACT_ADDRESS"
fi
echo ""
echo "🚀 Next steps:"
echo "  1. npm run dev      - Start development server"
echo "  2. Open http://localhost:3000"
echo "  3. Connect your wallet"
echo "  4. Start creating raffles!"
echo ""
echo "💾 Your configuration has been saved to .env.local"
echo ""
